@startuml
!include %TAWJA_HOME%/utils/uml/twj-plantuml-skin.iuml

'left to right direction

package ModuleSecurity {
    class User #FDFDAA
    note bottom : Quite all working tables audit the user.\nThose relations are not shown here.
    class Profile
    note bottom : Admin, Manager, Contributor, Follower.
    class Group
    class SecurityRight #DDDDDD
    SecurityRight " *" -- "1" User
    SecurityRight " *" -- "1" Profile
    SecurityRight " *" -- "1" Group
}

@enduml