@startuml
!include %TAWJA_HOME%/utils/uml/twj-plantuml-skin.iuml

'left to right direction

box "DevCOmputer"
    actor SystemManager
end box

box "Git\n(cloud)"
	participant GitInfraRepository
end box

box "Git\n(secured)"
	participant GitSecuredRepository
end box

box "ServerN"
	participant SystemMonitorN
	participant SystemDeployerN
	participant AppDeployerN
end box

@enduml