@startuml
!include %TAWJA_HOME%/utils/uml/twj-plantuml-skin.iuml

'left to right direction

start


partition "Development of Module" {

    repeat
        :Write Tawja Domain DSL XText Grammar;
        :Write/Update XText utilities classes;
        :Maven Build and Test to Generate the Parser;
        :Check Tawja Domain DSL ANTLR Grammar;

        :Write Tawja Domain DSL files to test;
        :Define all test use cases|

        if (Need new Tawja DSL logic?) then (YES)
            :Write/Update Tawja DSL plugin;
            :Write/Update Tawja DSL Generators;
        else (NO)
        endif

        :Maven Build and Test;
        :Manual Checks;
    repeat while (Answer the need?) is(NO) not(YES)

}

stop

@enduml
